#!/usr/bin/env bash
# Reverts README.md copy -- what is done by pre-commit
# Delete the README.md since the original at ~/.config/yadm/README.md still exists

cd || exit $?


declare -a files
files=(`cat ~/.config/yadm/hooks/files`)

for file in "${files[@]}"; do
    [[ -f "$HOME/$file" ]] && mv "$HOME/$file" "$HOME/.config/yadm/$file"
done
