#!/usr/bin/env bash
# Moves the README.md downloaded from github back to ~/.config/yadm/README.md
# so that changes made through the web interacted stay updated locally

cd || exit $?

declare -a files
files=(`cat ~/.config/yadm/hooks/files`)

for file in "${files[@]}"; do
    [[ -f "$HOME/$file" ]] && mv "$HOME/$file" "$HOME/.config/yadm/$file"
done
