#!/usr/bin/env bash
# Copy README for git repo to $HOME so that the github repo README will be updated
# post-commit moves the README.md back so as to not pollute $HOME

cd || exit $?

declare -a files
files=(`cat ~/.config/yadm/hooks/files`)

for file in "${files[@]}"; do 
    echo "copy $HOME/.config/yadm/${file} -> $HOME/${file}"
    ls "$HOME/.config/yadm/"
    cp "$HOME/.config/yadm/${file}" "$HOME/${file}"
    yadm add -f "$HOME/${file}"
done
